# Generated by Django 5.1.6 on 2025-03-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_bookinstance_borrowed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookinstance",
            old_name="borrowed",
            new_name="borrower",
        ),
    ]
